name: CI SNAPSHOT

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_snapshot:
    uses: artembilan/spring-github-workflows/.github/workflows/spring-artifactory-maven-snapshot.yml@main
    secrets:
      JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}