name: Merge Dependabot PR

on:
  pull_request:
    branches:
      - main

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all

    uses: artembilan/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@main