name: Promote Staged Milestone in Artifactory

on:
  workflow_call:
    inputs:
      buildName:
        description: 'The Artifactory Build Name'
        required: true
        type: string
      buildNumber:
        description: 'The Artifactory Build Number'
        required: true
        type: string

jobs:
  promote-milestone-with-jfrog:
    runs-on: ubuntu-latest
    steps:

      - uses: jfrog/setup-jfrog-cli@v3
        with:
          version: 2.50.4
        env:
          JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}

      - name: Promote Build
        run: jfrog rt build-promote ${{ inputs.buildName }} ${{ inputs.buildNumber }} libs-milestone-local