name: Promote Staged GA release from Artifactory to Maven Central

on:
  workflow_call:
    inputs:
      buildName:
        description: 'The Artifactory Build Name'
        required: true
        type: string
      buildNumber:
        description: 'The Artifactory Build Number'
        required: true
        type: string

    secrets:
      OSSRH_URL:
        required: true
      OSSRH_S01_TOKEN_USERNAME:
        required: true
      OSSRH_S01_TOKEN_PASSWORD:
        required: true
      OSSRH_STAGING_PROFILE_NAME:
        required: true
      GPG_PASSPHRASE:
        required: true
      GPG_PRIVATE_KEY:
        required: true
      JF_ARTIFACTORY_SPRING:
        required: true

env:
  JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}

jobs:
  release-to-central:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          repository: artembilan/spring-messaging-build-tools
          show-progress: false

      - uses: jfrog/setup-jfrog-cli@v3
        with:
          version: 2.51.1

      - name: Promote Build
        run: jfrog rt build-promote ${{ inputs.buildName }} ${{ inputs.buildNumber }} libs-release-local

      # Download released files
      - name: Download Release Files
        run: |
          jfrog rt download \
            --spec release-files-spec.json \
            --spec-vars "buildname=${{ inputs.buildName }};buildnumber=${{ inputs.buildNumber }}"

      # Create checksums, signatures and create staging repo on central and upload
      - uses: jvalkeal/nexus-sync@v0.0.2
        id: nexus
        with:
          url: ${{ secrets.OSSRH_URL }}
          username: ${{ secrets.OSSRH_S01_TOKEN_USERNAME }}
          password: ${{ secrets.OSSRH_S01_TOKEN_PASSWORD }}
          staging-profile-name: ${{ secrets.OSSRH_STAGING_PROFILE_NAME }}
          create: true
          upload: true
          generate-checksums: true
          pgp-sign: true
          upload-parallel: 10
          pgp-sign-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          pgp-sign-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          close: true
          release: true