name: Promote Staged Milestone in Artifactory

on:
  workflow_call:
    inputs:
      buildName:
        description: 'The Artifactory Build Name'
        required: true
        type: string
      buildNumber:
        description: 'The Artifactory Build Number'
        required: true
        type: string

    secrets:
      JF_ARTIFACTORY_SPRING:
        required: true

env:
  JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}

jobs:
  promote-milestone-with-jfrog:
    runs-on: ubuntu-latest
    steps:

      - uses: jfrog/setup-jfrog-cli@v3

      - name: Promote Build
        run: jfrog rt build-promote ${{ inputs.buildName }} ${{ inputs.buildNumber }} libs-milestone-local